namespace RemoteSupport.Signaling;

public static class OperatorPage
{
    public const string Html = """
<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Rotaniz Remote Support</title>
<style>
:root{color-scheme:dark;font-family:Segoe UI,Arial,sans-serif}html,body{width:100%;height:100%;overflow:hidden}body{margin:0;background:#0b1120;color:#e5edf8}header{display:flex;gap:12px;align-items:center;padding:14px 18px;background:#111a2e;border-bottom:1px solid #26324d;box-sizing:border-box;min-height:66px}h1{font-size:18px;margin:0 auto 0 0}input,button{font:inherit;border-radius:8px;border:1px solid #405071;padding:9px 12px}input{width:150px;background:#0b1120;color:white;letter-spacing:3px}button{background:#2f6feb;color:white;cursor:pointer}button:disabled{opacity:.5}.danger{background:#b42335}.status{font-size:13px;color:#9fb0ca}.stage{width:100vw;height:calc(100vh - 66px);display:flex;align-items:center;justify-content:center;padding:8px;box-sizing:border-box;background:#05070b}canvas{display:block;width:min(100%,calc((100vh - 82px)*16/9));height:auto;aspect-ratio:16/9;max-height:100%;background:#05070b;box-shadow:0 8px 40px #0008;outline:none;cursor:default;image-rendering:auto;object-fit:contain}.stage:fullscreen{width:100vw;height:100vh;padding:0;background:#000}.stage:fullscreen canvas{width:100vw;height:100vh;max-width:100vw;max-height:100vh;object-fit:contain;box-shadow:none;cursor:default}.hint{position:absolute;color:#7f91ae;pointer-events:none}
</style></head><body>
<header><h1>Rotaniz Remote Support</h1><input id="code" maxlength="9" inputmode="numeric" autocomplete="one-time-code" placeholder="9 haneli kod"><button id="connect" disabled>Bağlan</button><button id="fullscreen">Tam Ekran</button><button id="stop" class="danger" disabled>Bitir</button><span id="status" class="status">Bağlantı yok</span></header>
<main id="stage" class="stage"><div id="hint" class="hint">Bağlantı kodunu girin</div><canvas id="screen" tabindex="0"></canvas></main>
<script>
const code=document.querySelector('#code'),connect=document.querySelector('#connect'),fullscreen=document.querySelector('#fullscreen'),stop=document.querySelector('#stop'),status=document.querySelector('#status'),stage=document.querySelector('#stage'),canvas=document.querySelector('#screen'),hint=document.querySelector('#hint'),ctx=canvas.getContext('2d',{alpha:false});let controlWs=null,videoWs=null,framePixels=null,pendingFrame=null,painting=false,controlSent=false,controlState=null,videoDecoder=null;
const setStatus=t=>status.textContent=t;
code.oninput=()=>{code.value=code.value.replace(/\D/g,'').slice(0,9);connect.disabled=code.value.length!==9;if(code.value.length<9)setStatus(`${code.value.length}/9 hane girildi`)};code.onkeydown=e=>{if(e.key==='Enter'&&!connect.disabled)connect.click()};
connect.onclick=async()=>{const value=code.value.replace(/\D/g,'');if(value.length!==9){setStatus('9 haneli kod gerekli');return}connect.disabled=true;setStatus('Kod sunucuya gönderiliyor…');try{const r=await fetch('/v1/support-codes/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:value})});if(!r.ok)throw new Error(r.status===429?'Çok fazla deneme — bir dakika bekleyin':'Kod geçersiz veya destek alan taraf oturumu sonlandırmış');const s=await r.json(),proto='ascos.guest.'+s.guestToken,base=`${location.protocol==='https:'?'wss':'ws'}://${location.host}/v1/sessions/${s.sessionId}/signal?role=guest&channel=`;controlWs=new WebSocket(base+'control',proto);videoWs=new WebSocket(base+'video',proto);videoWs.binaryType='arraybuffer';let opened=0;const onopen=()=>{if(++opened===2){setStatus('Bağlandı — ekran bekleniyor');stop.disabled=false;canvas.focus()}};controlWs.onopen=onopen;videoWs.onopen=onopen;const onclose=()=>reset('Bağlantı kapandı — yeniden bağlanmak için istemcideki yeni kodu girin');controlWs.onclose=onclose;videoWs.onclose=onclose;controlWs.onerror=videoWs.onerror=()=>setStatus('WebSocket bağlantı hatası');controlWs.onmessage=e=>{if(typeof e.data!=='string')return;try{const m=JSON.parse(e.data);if(m.type==='control-result'){controlState=m.ok;const detail=[m.stage,m.error?`Win32 ${m.error}`:null,m.desktop].filter(Boolean).join(' · ');setStatus(m.ok?`Canlı — kontrol etkin${detail?' · '+detail:''}`:`Kontrol başarısız — ${detail||'tanı bilgisi yok'}`)}}catch{}};videoWs.onmessage=e=>{if(!(e.data instanceof ArrayBuffer))return;pendingFrame=e.data;pumpFrames()}}catch(e){reset(e.message)}};
async function pumpFrames(){if(painting)return;painting=true;try{while(pendingFrame){const newest=pendingFrame;pendingFrame=null;await drawFrame(newest)}}catch{setStatus('Görüntü paketi çözülemedi')}finally{painting=false}}
async function ensureVideoDecoder(){if(videoDecoder)return videoDecoder;if(typeof VideoDecoder==='undefined')throw new Error('WebCodecs H.264 desteği yok');const config={codec:'avc1.4D401F',optimizeForLatency:true,hardwareAcceleration:'prefer-hardware'};const support=await VideoDecoder.isConfigSupported(config);if(!support.supported)throw new Error('H.264 decoder desteklenmiyor');videoDecoder=new VideoDecoder({output:frame=>{if(canvas.width!==frame.displayWidth||canvas.height!==frame.displayHeight){canvas.width=frame.displayWidth;canvas.height=frame.displayHeight}ctx.drawImage(frame,0,0,canvas.width,canvas.height);frame.close();hint.hidden=true;if(controlState===null)setStatus('Canlı — DXGI/H.264 görüntü alınıyor')},error:error=>setStatus('H.264 decoder hatası: '+error.message)});videoDecoder.configure(config);return videoDecoder}
async function drawFrame(buffer){const b=new Uint8Array(buffer);let w,h,pixels;if(b[0]===4){if(b.length<15)return;w=b[2]|b[3]<<8;h=b[4]|b[5]<<8;const timestamp100ns=new DataView(buffer).getBigInt64(6,true),decoder=await ensureVideoDecoder();decoder.decode(new EncodedVideoChunk({type:(b[1]&1)!==0?'key':'delta',timestamp:Number(timestamp100ns/10n),data:b.subarray(14)}));return}else if(b[0]===3){if(b.length<6)return;w=b[1]|b[2]<<8;h=b[3]|b[4]<<8;const image=await createImageBitmap(new Blob([b.subarray(5)],{type:'image/jpeg'}));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.drawImage(image,0,0,w,h);image.close()}else if(b[0]===1){if(b.length<5)return;w=b[1]|b[2]<<8;h=b[3]|b[4]<<8;if(b.length!==5+w*h*4)return;pixels=b.subarray(5);framePixels=pixels.slice()}else if(b[0]===2){if(b.length<7||typeof DecompressionStream==='undefined')throw new Error('gzip unavailable');const keyFrame=(b[1]&1)!==0;w=b[2]|b[3]<<8;h=b[4]|b[5]<<8;const stream=new Blob([b.subarray(6)]).stream().pipeThrough(new DecompressionStream('gzip'));pixels=new Uint8Array(await new Response(stream).arrayBuffer());if(pixels.length!==w*h*4)throw new Error('invalid frame');if(keyFrame||!framePixels||framePixels.length!==pixels.length)framePixels=pixels;else for(let i=0;i<pixels.length;i++)framePixels[i]^=pixels[i];if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const out=new Uint8ClampedArray(w*h*4);for(let i=0;i<out.length;i+=4){out[i]=framePixels[i+2];out[i+1]=framePixels[i+1];out[i+2]=framePixels[i];out[i+3]=255}ctx.putImageData(new ImageData(out,w,h),0,0)}else return;hint.hidden=true;if(controlState===null)setStatus('Canlı — görüntü alınıyor')}
stop.onclick=()=>{controlWs?.close(1000,'operator stopped');videoWs?.close(1000,'operator stopped');reset('Sonlandırıldı')};
fullscreen.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.requestFullscreen()}catch{setStatus('Tam ekran bu tarayıcıda kullanılamıyor')}};document.onfullscreenchange=()=>{fullscreen.textContent=document.fullscreenElement?'Tam Ekrandan Çık':'Tam Ekran';canvas.focus()};
function reset(message){controlWs=null;videoWs=null;framePixels=null;pendingFrame=null;painting=false;controlSent=false;controlState=null;lastPointerPos=null;pressedButtons.clear();if(videoDecoder){try{videoDecoder.close()}catch{}videoDecoder=null}connect.disabled=code.value.length!==9;stop.disabled=true;setStatus(message)}
function send(o){if(controlWs?.readyState===WebSocket.OPEN){controlWs.send(JSON.stringify(o));if(!controlSent){controlSent=true;setStatus('Canlı — kontrol komutu gönderildi')}}}
function pos(e){
 const r=canvas.getBoundingClientRect(),sourceW=canvas.width||16,sourceH=canvas.height||9,sourceAspect=sourceW/sourceH,boxAspect=r.width/r.height;
 let contentW=r.width,contentH=r.height,offsetX=0,offsetY=0;
 if(boxAspect>sourceAspect){contentW=r.height*sourceAspect;offsetX=(r.width-contentW)/2}else{contentH=r.width/sourceAspect;offsetY=(r.height-contentH)/2}
 const localX=e.clientX-r.left-offsetX,localY=e.clientY-r.top-offsetY;
 if(localX<0||localY<0||localX>contentW||localY>contentH)return null;
 return{normalizedX:Math.max(0,Math.min(1,localX/contentW)),normalizedY:Math.max(0,Math.min(1,localY/contentH))};
}
let lastMove=0,lastPointerPos=null,pressedButtons=new Set();canvas.onpointermove=e=>{const n=performance.now(),p=pos(e);if(!p||n-lastMove<16||controlWs?.bufferedAmount>16384)return;lastMove=n;lastPointerPos=p;send({type:'move',...p})};canvas.onpointerdown=e=>{const p=pos(e);if(!p)return;lastPointerPos=p;e.preventDefault();canvas.focus();canvas.setPointerCapture(e.pointerId);pressedButtons.add(e.button);send({type:'button',button:e.button,down:true,...p})};canvas.onpointerup=e=>{const p=pos(e)||lastPointerPos;e.preventDefault();pressedButtons.delete(e.button);if(p)send({type:'button',button:e.button,down:false,...p});if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)};canvas.onpointercancel=e=>{const p=pos(e)||lastPointerPos;if(p)for(const button of pressedButtons)send({type:'button',button,down:false,...p});pressedButtons.clear()};canvas.onwheel=e=>{const p=pos(e);if(!p)return;lastPointerPos=p;e.preventDefault();send({type:'wheel',delta:Math.sign(-e.deltaY)*120,...p})};canvas.oncontextmenu=e=>e.preventDefault();canvas.onkeydown=e=>{e.preventDefault();if(e.repeat)return;send({type:'key',key:e.key,code:e.code,down:true})};canvas.onkeyup=e=>{e.preventDefault();send({type:'key',key:e.key,code:e.code,down:false})};
</script></body></html>
""";
}
