namespace RemoteSupport.Signaling;

public static class OperatorPage
{
    public const string Html = """
<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Rotaniz Remote Support</title>
<style>
:root{color-scheme:dark;font-family:Segoe UI,Arial,sans-serif}html,body{width:100%;height:100%;overflow:hidden}body{margin:0;background:#0b1120;color:#e5edf8}header{display:flex;gap:12px;align-items:center;padding:14px 18px;background:#111a2e;border-bottom:1px solid #26324d;box-sizing:border-box;min-height:66px}h1{font-size:18px;margin:0 auto 0 0}input,button{font:inherit;border-radius:8px;border:1px solid #405071;padding:9px 12px}input{width:150px;background:#0b1120;color:white;letter-spacing:3px}button{background:#2f6feb;color:white;cursor:pointer}button:disabled{opacity:.5}.danger{background:#b42335}.status{font-size:13px;color:#9fb0ca}.stage{width:100vw;height:calc(100vh - 66px);display:flex;align-items:center;justify-content:center;padding:8px;box-sizing:border-box;background:#05070b}canvas{display:block;width:min(100%,calc((100vh - 82px)*16/9));height:auto;aspect-ratio:16/9;max-height:100%;background:#05070b;box-shadow:0 8px 40px #0008;outline:none;cursor:default;image-rendering:auto}.stage:fullscreen{width:100vw;height:100vh;padding:0;background:#000}.stage:fullscreen canvas{width:100vw;height:100vh;max-width:100vw;max-height:100vh;object-fit:contain;box-shadow:none;cursor:default}.hint{position:absolute;color:#7f91ae;pointer-events:none}
</style></head><body>
<header><h1>Rotaniz Remote Support</h1><input id="code" maxlength="9" inputmode="numeric" autocomplete="one-time-code" placeholder="9 haneli kod"><button id="connect" disabled>Bağlan</button><button id="fullscreen">Tam Ekran</button><button id="stop" class="danger" disabled>Bitir</button><span id="status" class="status">Bağlantı yok</span></header>
<main id="stage" class="stage"><div id="hint" class="hint">Bağlantı kodunu girin</div><canvas id="screen" tabindex="0"></canvas></main>
<script>
const code=document.querySelector('#code'),connect=document.querySelector('#connect'),fullscreen=document.querySelector('#fullscreen'),stop=document.querySelector('#stop'),status=document.querySelector('#status'),stage=document.querySelector('#stage'),canvas=document.querySelector('#screen'),hint=document.querySelector('#hint'),ctx=canvas.getContext('2d',{alpha:false});let ws=null,frameQueue=Promise.resolve(),framePixels=null,controlSent=false,controlState=null;
const setStatus=t=>status.textContent=t;
code.oninput=()=>{code.value=code.value.replace(/\D/g,'').slice(0,9);connect.disabled=code.value.length!==9;if(code.value.length<9)setStatus(`${code.value.length}/9 hane girildi`)};code.onkeydown=e=>{if(e.key==='Enter'&&!connect.disabled)connect.click()};
connect.onclick=async()=>{const value=code.value.replace(/\D/g,'');if(value.length!==9){setStatus('9 haneli kod gerekli');return}connect.disabled=true;setStatus('Kod sunucuya gönderiliyor…');try{const r=await fetch('/v1/support-codes/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:value})});if(!r.ok)throw new Error(r.status===429?'Çok fazla deneme — bir dakika bekleyin':'Kod geçersiz veya destek alan taraf oturumu sonlandırmış');const s=await r.json();setStatus('Kod doğrulandı — host bağlantısı bekleniyor');const proto='ascos.guest.'+s.guestToken;ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/v1/sessions/${s.sessionId}/signal?role=guest`,proto);ws.binaryType='arraybuffer';ws.onopen=()=>{setStatus('Bağlandı — ekran bekleniyor');stop.disabled=false;canvas.focus()};ws.onclose=()=>reset('Bağlantı kapandı — yeniden bağlanmak için istemcideki yeni kodu girin');ws.onerror=()=>setStatus('WebSocket bağlantı hatası');ws.onmessage=e=>{if(typeof e.data==='string'){try{const m=JSON.parse(e.data);if(m.type==='control-result'){controlState=m.ok;setStatus(m.ok?'Canlı — kontrol etkin':'Canlı — kontrol istemci tarafından reddedildi')}}catch{}return}if(!(e.data instanceof ArrayBuffer))return;frameQueue=frameQueue.then(()=>drawFrame(e.data)).catch(()=>setStatus('Görüntü paketi çözülemedi'))}}catch(e){reset(e.message)}};
async function drawFrame(buffer){const b=new Uint8Array(buffer);let w,h,pixels;if(b[0]===1){if(b.length<5)return;w=b[1]|b[2]<<8;h=b[3]|b[4]<<8;if(b.length!==5+w*h*4)return;pixels=b.subarray(5);framePixels=pixels.slice()}else if(b[0]===2){if(b.length<7||typeof DecompressionStream==='undefined')throw new Error('gzip unavailable');const keyFrame=(b[1]&1)!==0;w=b[2]|b[3]<<8;h=b[4]|b[5]<<8;const stream=new Blob([b.subarray(6)]).stream().pipeThrough(new DecompressionStream('gzip'));pixels=new Uint8Array(await new Response(stream).arrayBuffer());if(pixels.length!==w*h*4)throw new Error('invalid frame');if(keyFrame||!framePixels||framePixels.length!==pixels.length)framePixels=pixels;else for(let i=0;i<pixels.length;i++)framePixels[i]^=pixels[i]}else return;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const out=new Uint8ClampedArray(w*h*4);for(let i=0;i<out.length;i+=4){out[i]=framePixels[i+2];out[i+1]=framePixels[i+1];out[i+2]=framePixels[i];out[i+3]=255}ctx.putImageData(new ImageData(out,w,h),0,0);hint.hidden=true;if(controlState===null)setStatus('Canlı — görüntü alınıyor')}
stop.onclick=()=>{if(ws)ws.close(1000,'operator stopped');reset('Sonlandırıldı')};
fullscreen.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.requestFullscreen()}catch{setStatus('Tam ekran bu tarayıcıda kullanılamıyor')}};document.onfullscreenchange=()=>{fullscreen.textContent=document.fullscreenElement?'Tam Ekrandan Çık':'Tam Ekran';canvas.focus()};
function reset(message){ws=null;framePixels=null;frameQueue=Promise.resolve();controlSent=false;controlState=null;connect.disabled=code.value.length!==9;stop.disabled=true;setStatus(message)}
function send(o){if(ws?.readyState===WebSocket.OPEN){ws.send(JSON.stringify(o));if(!controlSent){controlSent=true;setStatus('Canlı — kontrol komutu gönderildi')}}}
function pos(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(65535,Math.round((e.clientX-r.left)/r.width*65535))),y:Math.max(0,Math.min(65535,Math.round((e.clientY-r.top)/r.height*65535)))}}
let lastMove=0;canvas.onmousemove=e=>{const n=performance.now();if(n-lastMove<16)return;lastMove=n;send({type:'move',...pos(e)})};canvas.onmousedown=e=>{e.preventDefault();canvas.focus();send({type:'button',button:e.button,down:true,...pos(e)})};canvas.onmouseup=e=>send({type:'button',button:e.button,down:false,...pos(e)});canvas.onwheel=e=>{e.preventDefault();send({type:'wheel',delta:Math.sign(-e.deltaY)*120,...pos(e)})};canvas.oncontextmenu=e=>e.preventDefault();canvas.onkeydown=e=>{e.preventDefault();send({type:'key',key:e.key,code:e.code,down:true})};canvas.onkeyup=e=>{e.preventDefault();send({type:'key',key:e.key,code:e.code,down:false})};
</script></body></html>
""";
}
